QUESTION 1:

In [ ]:
import numpy as np

In [ ]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

QUESTION 2:

In [ ]:
list1=[]
list2=[]
print("The elemnts of List1 are:")
for i in range(5):
    i=int(input())
    list1.append(i)
print()
print("The elemnts of List2 are:")
for i in range(5):
    i=int(input())
    list2.append(i)
np.array(list1)
np.array(list2)
print()
print(np.concatenate((list1,list2),axis=None))
print()
np.sort(np.concatenate((list1,list2)))

The elemnts of List1 are:
78
32
56
879
43

The elemnts of List2 are:
35
76
324
87
980

[ 78  32  56 879  43  35  76 324  87 980]



array([ 32,  35,  43,  56,  76,  78,  87, 324, 879, 980])

QUESTION 3:

In [ ]:
ar=np.array( [ [12,24,36],[48,60,72],[84,96,108] ] )
print("Dimensions of ndarray is:",np.shape(ar))
print()
print("Size of ndarrary",np.size(ar))


Dimensions of ndarray is: (3, 3)

Size of ndarrary 9


QUESTION 4:

In [ ]:
ar1=np.array( [0,1,2,3,4,5,6,7,8,9,10,11] )
print("1D array is:",ar1)
print()
ar2=np.reshape(ar1,(6,2))
print("2D array is:",ar2)

1D array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]

2D array is: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


QUESTION 5:

In [ ]:
ar1=np.array( [ [2,4,6],[8,10,12] ] )
ar2=np.array( [ [1,3,5],[7,9,11] ] )
ar_1=np.square(ar1)
print(ar_1)
print()
ar_2=np.square(ar2)
print(ar_2)
print()
newar1=np.hstack((ar_1,ar_2))
print(newar1)
print()
newar2=np.vstack((ar_1,ar_2))
print(newar2)

[[  4  16  36]
 [ 64 100 144]]

[[  1   9  25]
 [ 49  81 121]]

[[  4  16  36   1   9  25]
 [ 64 100 144  49  81 121]]

[[  4  16  36]
 [ 64 100 144]
 [  1   9  25]
 [ 49  81 121]]


QUESTION 6:

In [ ]:
arr=np.array([10,20,10,35,55,20,35,90,10,55])
print(arr)
np.unique(arr)
print()
np.unique(arr,return_counts=True)

[10 20 10 35 55 20 35 90 10 55]



(array([10, 20, 35, 55, 90]), array([3, 2, 2, 2, 1]))